DemoDropZone/Models/ErrorViewModel.cs
namespace DemoDropZone.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DemoDropZone/Controllers/DemoUploadController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;

namespace DemoDropZone.Controllers
{
    public class DemoUploadController : Controller
    {
        [HttpGet]
        public IActionResult UploadFiles()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> UploadFiles(IFormFile filedata)
        {
            var files = HttpContext.Request.Form.Files;
            if (files.Any())
            {
                foreach (var file in files)
                {
                    if (file.Length > 0)
                    {
                        //Getting FileName
                        var fileName = Path.GetFileName(file.FileName);
                        //Assigning Unique Filename (Guid)
                        var myUniqueFileName = Convert.ToString(Guid.NewGuid().ToString("N"));
                        //Getting file Extension
                        var fileExtension = Path.GetExtension(fileName);
                        // concatenating  FileName + FileExtension
                        var newFileName = String.Concat(myUniqueFileName, fileExtension);
                        await using var target = new MemoryStream();
                        await file.CopyToAsync(target);
                        var physicalPath = $"{new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "UploadedFiles")).Root}{$@"{fileName}"}";
                        string filePath = $"/UploadedFiles/{fileName}";
                        await using FileStream fs = System.IO.File.Create(physicalPath);
                        await file.CopyToAsync(fs);
                        fs.Flush();
                    }
                }

                return Json(new { status = true, Message = "Files Uploaded Successfully!" });
            }

            return View();
        }

    }
}

DemoDropZone/Controllers/HomeController.cs
using DemoDropZone.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DemoDropZone.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DemoDropZone/Views/DemoUpload/UploadFiles.cshtml
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Files Uploads</h3>
        </div>
        <div class="card-body register-card-body">
            <div class="form-row">
                <div class="col-md-12" id="dropzone">
                    <form asp-controller="DemoUpload" autocomplete="off" asp-antiforgery="true" class="dropzone"
                          id="demo-upload" enctype="multipart/form-data" asp-action="UploadFiles" method="post">
                        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                        <div class="form-row">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="button" id="btnupload" class="btn btn-success">Upload Files</button>
           
            <a class="btn btn-danger" asp-controller="DemoUpload" asp-action="UploadFiles">Clear</a>

        </div>
    </div>
</div>

@section Scripts{
<link href="~/js/dropzone/dropzone.min.css" rel="stylesheet" />
<script src="~/js/dropzone/dropzone.min.js"></script>


<script>
    Dropzone.autoDiscover = false;
    $(function () {
        var dz = null;
        $("#demo-upload").dropzone({
            autoProcessQueue: false,
            paramName: "File Upload",
            maxFilesize: 5, //mb
            maxThumbnailFilesize: 1, //mb
            maxFiles: 5,
            parallelUploads: 5,
            acceptedFiles: ".jpeg,.png,.jpg",
            uploadMultiple: true,
            addRemoveLinks: true,
     
            init: function () 
            {
                dz = this;
                $("#btnupload").click(function () 
                {
                    dz.processQueue();
                    $(this).attr("disabled", "disabled");
                });
            },
            success: function (file) 
            {
                var preview = $(file.previewElement);
                preview.addClass("dz-success text-success");
                setTimeout(function () 
                {
                    dz.removeFile(file);
                
                }, 2000);

            },
            queuecomplete: function () 
            {
                alert('Files Uploaded Successfully!');
            },
            dictDefaultMessage: "Drag and drop your files here to upload.",
            dictRemoveFile: "Remove"
        });
 
    });
  
</script>

}

DemoDropZone/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DemoDropZone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoDropZone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoDropZone.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoDropZone</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DemoDropZone - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>